name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select GCP environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod
      aiven-secret:
        description: Aiven secret med korrekte rettigheter to mount, f.eks. aiven-org-kafka-manager-cg37ax1v
        required: true

env:
  POOL: nav-${{ github.event.inputs.environment }}
  SECRET: ${{ github.event.inputs.aiven-secret }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: org
          image_suffix: kafka-cli
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy til ${{ github.event.inputs.environment }}-gcp
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: .nais/nais.yml
          PRINT_PAYLOAD: true
          CLUSTER: ${{ github.event.inputs.environment }}-gcp
          VAR: image=${{needs.build.outputs.image}},pool=${{ env.POOL }},secret=${{ env.SECRET }}
