name: Deploy kafka-manager

on:
  push:
    branches:
      - 'main'
    paths:
      - '.nais/org-kafka-manager-dev.yml'
      - '.nais/org-kafka-manager-prod.yml'
      - '.github/workflows/deploy-kafka-manager.yml'
  workflow_dispatch:

jobs:
  deploy-dev:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: Deploy til dev-gcp
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: .nais/org-kafka-manager-dev.yml
          CLUSTER: dev-gcp

  deploy-prod:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: Deploy til prod-gcp
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: .nais/org-kafka-manager-prod.yml
          CLUSTER: prod-gcp